FROM ruby:2.6.3-alpine AS build-env
ARG RAILS_ROOT=/backend
ARG BUILD_PACKAGES="build-base curl-dev git snappy"
ARG DEV_PACKAGES="postgresql-dev yaml-dev zlib-dev nodejs yarn build-base libexecinfo automake autoconf libtool"
ARG RUBY_PACKAGES="tzdata"
ENV RAILS_ENV=production
ENV NODE_ENV=production
ENV BUNDLE_APP_CONFIG="$RAILS_ROOT/.bundle"
WORKDIR $RAILS_ROOT
# install packages
RUN apk update \
    && apk upgrade \
    && apk add --update --no-cache $BUILD_PACKAGES $DEV_PACKAGES \
       $RUBY_PACKAGES 

RUN gem install bundler -v 2.1.4

COPY Gemfile* package.json ./
RUN bundle install --path=vendor/bundle \
# Remove unneeded files (cached *.gem, *.o, *.c)
    && rm -rf vendor/bundle/ruby/2.6.0/cache/*.gem \
    && find vendor/bundle/ruby/2.6.0/gems/ -name "*.c" -delete \
    && find vendor/bundle/ruby/2.6.0/gems/ -name "*.o" -delete

RUN yarn install
COPY . .
RUN bin/rails assets:precompile

# Remove folders not needed in resulting image
RUN rm -rf node_modules tmp/cache app/assets vendor/assets spec

FROM ruby:2.6.3-alpine
ARG RAILS_ROOT=/backend
ARG PACKAGES="tzdata postgresql-client nodejs bash"

ENV BUNDLE_APP_CONFIG="$RAILS_ROOT/.bundle"

WORKDIR $RAILS_ROOT

# install packages
RUN apk update \
    && apk upgrade \
    && apk add --update --no-cache $PACKAGES

RUN gem install bundler -v 2.1.4

COPY --from=build-env $RAILS_ROOT $RAILS_ROOT
EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]



# RUN mkdir /backend

# WORKDIR /backend

# ENV BUNDLER_VERSION=2.1.4

# RUN gem install bundler:2.1.4

# COPY Gemfile /backend/Gemfile
# COPY Gemfile.lock /backend/Gemfile.lock
# RUN bundle install
# COPY . /backend

# ENV POSTGRES_HOST 192.168.0.103
# ENV POSTGRES_PORT 5432
# ENV POSTGRES_USERNAME postgres
# ENV POSTGRES_PASSWORD postgres

# # Add a script to be executed every time the container starts.
# COPY entrypoint.sh /usr/bin/
# RUN chmod +x /usr/bin/entrypoint.sh
# EXPOSE 3000

# ENTRYPOINT ["entrypoint.sh"]